services:
  mariadb:
    image: mariadb:11
    container_name: spity-mariadb
    environment:
      MARIADB_ROOT_PASSWORD: q15ZiNTea5E1YOmll2nx16u10dFIb1s45xX9yqBSQUg
      MARIADB_DATABASE: spity
      MARIADB_USER: spity
      MARIADB_PASSWORD: q15ZiNTea5E1YOmll2nx16u10dFIb1s45xX9yqBSQUg
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    container_name: spity-phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mariadb
      PMA_USER: spity
      PMA_PASSWORD: q15ZiNTea5E1YOmll2nx16u10dFIb1s45xX9yqBSQUg
    depends_on:
      - mariadb

volumes:
  mariadb_data:
