"""Keep the oral narrative aligned with the existing Bloc 1, 2 and 4 sources."""

def align(slides):
    by_number = {slide['number']: slide for slide in slides}
    def update(number, **fields):
        by_number[number].update(fields)
    def replace(number, old, new):
        assert old in by_number[number]['script'], (number, old)
        by_number[number]['script'] = by_number[number]['script'].replace(old, new, 1)
    def source(number, value):
        by_number[number]['source'] += ' ' + value

    update(2, title="Le besoin d’Altitude Grimpe", nature='B1, commanditaire fictif et produit réel', script="""Je reprends le commanditaire du Bloc 1 : le Collectif Altitude Grimpe, association fictive représentée par Claire Martin. Le cadre reste une zone pilote autour de Lyon et Grenoble. Son besoin est de centraliser des usages aujourd'hui dispersés : trouver un partenaire, consulter les lieux et organiser des sorties.

Pour cette soutenance, je retiens le parcours déjà développé dans le Bloc 2. Le grimpeur recherche une personne compatible et rejoint un événement. Le club organise cette sortie et retrouve les participants autorisés. Ce choix relie le besoin initial à un résultat démontrable. La capture montre le répertoire de lieux du produit local. Elle illustre le contexte géographique, sans prétendre que toutes les fonctions de la vision initiale sont validées.""", source='B1 : C1.1.1, p. 2 ; C1.4.1, p. 4-5. B2 : 16_DOSSIER_FINAL_BC02, F01-F10. Capture locale du 15 septembre 2026, données de test.', transition='Les quatre blocs abordent ce même projet sous des angles complémentaires.')

    update(3, title='Un projet, quatre blocs', script="""Le Bloc 1 pose le besoin, les acteurs, l'architecture cible et le budget global. Le Bloc 2 présente le prototype développé, ses tests, ses corrections et sa livraison. Le Bloc 3 explique comment piloter un lot : planifier, suivre les écarts, arbitrer et préparer la validation. Le Bloc 4 documente ensuite les responsabilités de maintenance, les anomalies et le support.

Cette lecture est une articulation de compétences. Le dossier de maintenance d'août existe déjà avant cette préparation de septembre. Le logiciel et ses traces sont réels. Le commanditaire du Bloc 1 et l'équipe CP, DEV, QA du scénario sont fictifs. Je conserve cette distinction, également présente dans le cas support du Bloc 4, sans transformer une simulation en échange client réel.""", source='B1 : C1.1.1 et C1.4.2. B2 : 16_DOSSIER_FINAL_BC02. B4 : DOSSIER_BLOC_04 et B4-C433-01. Référentiel p. 11. COHERENCE_INTER_BLOCS.md.', action='Montrer les quatre blocs, puis préciser la nature réelle ou fictive des éléments.', transition="Je zoome maintenant sur l'organisation du lot pédagogique.")

    replace(5, "Le planning couvre quinze jours ouvrés relatifs. J1 à J15 désignent les jours du cas, pas des dates historiques du développement de Spity. Je conserve la référence initiale pour pouvoir expliquer les changements au lieu d'effacer les retards.", "Le planning porte sur un lot pédagogique de préparation et de stabilisation d'une démonstration, adossé au produit existant. Ses quinze jours ouvrés relatifs ne représentent pas tout le développement de Spity. Les quatre-vingt-deux jours-homme du diaporama Bloc 1 concernent l'estimation globale du MVP. Ici, J1 à J15 désignent des jours du cas, et non des jalons globaux du cadrage.")
    source(5, 'B1 : diaporama, p. 21, estimation globale distincte du lot B3.')
    replace(6, "Le scénario distingue un chef de projet, un développeur et un testeur UX.", "Le Bloc 2 décrit les réalisations de Dorian. Ici, le scénario répartit les responsabilités entre trois rôles fictifs : chef de projet, développeur et testeur UX.")
    source(6, 'B1 : C1.1.1, p. 3. B2 : déclaration de périmètre du dossier final. La répartition CP/DEV/QA reste simulée.')

    update(8, title='Le budget de référence et le suivi du lot', script="""Je conserve le budget présenté dans le diaporama du Bloc 1 : quarante-quatre mille deux cent cinquante euros. Il comprend quatre-vingt-deux jours-homme à quatre cent cinquante euros, soit trente-six mille neuf cents euros de développement, puis les postes de lancement détaillés en annexe.

Le graphique suit un périmètre plus limité : notre cas de préparation de démonstration, valorisé en heures par rôle. La référence de ce lot est de quatre mille deux cent soixante-dix euros. À J10, sa prévision atteint quatre mille quatre cent soixante-cinq euros. L'écart de cent quatre-vingt-quinze euros représente environ quatre virgule six pour cent.

La réserve de quatre cent vingt-sept euros porte le plafond du lot à quatre mille six cent quatre-vingt-dix-sept euros. Il reste deux cent trente-deux euros de marge. Toute demande est examinée avec cette marge et la capacité des rôles.

Le classeur détaille ces calculs. Les charges du cas sont simulées : elles ne prouvent pas une consommation du budget global. Je conserve les unités et les périmètres pour éviter d'additionner des montants qui recouvrent des travaux communs.""", source='Diaporama B1, p. 21-22 : 82 j-h, 450 EUR/j, total 44 250 EUR. A03, A09 et classeur : cas B3 distinct. reference-bloc-01.json et COHERENCE_INTER_BLOCS.md.', action='Nommer le budget global B1, puis lire les trois repères du suivi détaillé du lot.')

    source(11, 'B2 : 19_RETOUR_EXPERIENCE_ET_CHOIX_TECHNIQUES, section 8. L’arbitrage B3 reprend le même événement et en explicite le raisonnement de pilotage.')
    source(12, 'B1 : diaporama p. 20-21, topos Should dans la vision cible. Le report concerne ce lot pédagogique ; il ne supprime pas la fonctionnalité du projet.')
    replace(14, "Une personne absente doit pouvoir comprendre la décision sans reconstituer toute une conversation.", "Le Bloc 4 applique aussi ce principe dans son cas support fictif : contexte fonctionnel transmis au mainteneur, puis retour sur la cause et les vérifications.")
    source(14, 'B4 : B4-C433-01, exemple de transmission support/mainteneur explicitement simulée, réutilisable comme méthode de communication.')
    replace(17, "Le suivi client repose sur trois points dans le scénario.", "Je reprends Claire Martin pour le Collectif Altitude Grimpe, commanditaire fictif du Bloc 1. Son suivi repose sur trois points dans le scénario.")
    source(17, 'B1 : C1.1.1 p. 2. CL représente Claire Martin pour le Collectif Altitude Grimpe, tous deux fictifs. A07 ne constitue pas un échange réel.')
    source(18, 'Les objectifs de NPS, de rétention et d’acquisition du Bloc 1 sont des cibles ; aucun résultat client réel n’en découle. B4-C433-01 est une simulation de support.')
    replace(18, "Elle ne vaut ni zéro ni cent pour cent.", "Les objectifs de NPS et de rétention du Bloc 1 restent des cibles, sans résultat constaté.")
    update(19, script="""Je passe à la démonstration locale, sur le même parcours grimpeur et club que dans le Bloc 2. Les comptes contiennent des données fictives. Je montre d'abord la recherche d'un partenaire, puis les inscriptions et les participants côté club. Comme le rappelle le Bloc 4, une validation locale ne prouve pas une mise à jour de la production.""")
    source(19, 'B2 : F03-F08. B4 : B4-C421-02 et dossier-jury/01_CADRAGE_PROJET, distinction local, staging et production. État de production historique non réactualisé.')
    update(22, title='La transmission à la maintenance', script="""Le Bloc 1 donne le besoin et la vision de Spity. Le Bloc 2 apporte le logiciel et les preuves de réalisation. Dans le Bloc 3, j'ai organisé un lot limité, interprété ses écarts et expliqué les décisions qui protègent la démonstration.

Le relais vers le Bloc 4 repose sur des éléments concrets : version identifiée, anomalies qualifiées, réserves et critères de vérification. Son registre et son processus de support existent déjà dans le dossier de maintenance. Je peux m'appuyer sur eux pour préparer cette transmission. Je conserve les limites annoncées : le management présenté reste fictif et aucune validation client réelle n'est inventée. Le pilotage doit rendre la prochaine action compréhensible et vérifiable, y compris après la soutenance.""", source='B4 : DOSSIER_BLOC_04, registres d’anomalies et de versions ; B4-C433-01, support simulé. B3 : A07 et A08.', action='Relier les réserves de démonstration à une anomalie ou une amélioration suivie dans le cadre de maintenance.', transition='Je suis prêt à expliquer les choix et à retrouver les pièces correspondantes.')
    update(25, title='Des contrôles datés et contextualisés', nature='Annexe, résultats historiques et contrôles locaux', script="""Le dossier BC02 du 23 juillet rapporte 126 tests unitaires et six scénarios navigateur. Le Bloc 4 du 13 août rapporte 152 tests Jest et distingue 43 tests de maintenance, avec onze scénarios MariaDB et six recettes. La préparation locale du Bloc 3 du 14 septembre rapporte 389 tests unitaires dans 72 suites et six scénarios navigateur. Les versions, configurations et périmètres diffèrent. Ces totaux ne mesurent pas une progression de qualité et ne doivent pas être additionnés. La recette B3 utilise next dev localement ; elle ne rejoue pas la CI standalone historique. Aucun résultat client réel n'a été trouvé dans les pièces examinées.""", source='B2 : 16_DOSSIER_FINAL_BC02, Résultats vérifiés, 23 juillet 2026. B4 : DOSSIER_BLOC_04, résumé du 13 août 2026. B3 : VERIFICATION.md et preuves/verification.json, 14 septembre 2026. Cadre officiel : référentiel p. 11-14, modalités p. 6, 8 et 11, grille BC03. Voir COHERENCE_INTER_BLOCS.md.')
