import fs from 'node:fs/promises';
import path from 'node:path';
import {createRequire} from 'node:module';
import {pathToFileURL} from 'node:url';
process.on('uncaughtException',error=>{console.error(error.stack);process.exit(1);});
const root=process.cwd(), tmp=path.join(root,'tmp/bloc3/build');
process.env.RUNTIME_NODE_MODULES ??= path.join(tmp,'node_modules');
const require=createRequire(path.join(tmp,'resolver.cjs'));
const {Presentation,PresentationFile,FileBlob}=await import(pathToFileURL(require.resolve('@oai/artifact-tool')).href);
const skill=process.env.BLOC3_PRESENTATION_SKILL??'C:/Users/JOLYDorian/.codex/plugins/cache/openai-primary-runtime/presentations/26.909.11809/skills/presentations';
const runtimePython=process.env.BLOC3_PYTHON??'C:/Users/JOLYDorian/.cache/codex-runtimes/codex-primary-runtime/dependencies/python/python.exe';
const {finalizePresentation,resolvePresentationFont}=await import(pathToFileURL(path.join(skill,'container_tools/artifact_tool_utils.mjs')).href);
const font=resolvePresentationFont({fontFamily:'Arial',availableFonts:['Arial']});
const ink='#18312D', green='#246B58', pale='#EDF3EF', gold='#CF9456';
const p=Presentation.create({slideSize:{width:1280,height:720}});
const plan=[];const tableOwners=[];
function text(s,value,x,y,w,h,size=27,bold=false,color=ink){const b=s.shapes.add({geometry:'textbox',position:{left:x,top:y,width:w,height:h},fill:'none',line:{fill:'none',width:0}});b.text=value;b.text.style={typeface:font,fontSize:size,bold,color,autoFit:'none'};return b;}
function slide(title,minutes,nature,notes){const s=p.slides.add();s.background.fill='#FFFFFF';const n=plan.length+1;text(s,title,64,44,1152,116,44,true);text(s,`${nature}  ·  ${n}`,64,667,1140,28,18,false,'#56665F');s.speakerNotes.textFrame.setText(notes);plan.push({number:n,title,minutes,nature,notes});return s;}
function lines(s,items,x=72,y=185,w=1100,gap=108){items.forEach((item,i)=>{if(Array.isArray(item)){text(s,item[0],x,y+i*gap,w,40,29,true,green);text(s,item[1],x,y+i*gap+43,w,64,26);}else{text(s,item,x,y+i*gap,w,84,29);}});}
function table(s,values,widths,top=180,height=388){const t=s.tables.add({rows:values.length,columns:values[0].length,left:64,top,width:1152,height,values,columnWidths:widths});tableOwners.push(plan.length);t.borders.assign({style:'solid',fill:'#FFFFFF',width:1});for(let i=0;i<values.length;i++){t.rows[i].height=height/values.length;for(let j=0;j<values[0].length;j++){const c=t.getCell(i,j);c.fill=i===0?green:i%2?pale:'#FFFFFF';c.text.style={typeface:font,fontSize:23,bold:i===0,color:i===0?'#FFFFFF':ink};}}return t;}
async function image(s,file,x,y,w,h,fit='contain'){s.images.add({blob:new Uint8Array(await fs.readFile(path.join(root,file))),contentType:file.endsWith('.png')?'image/png':'image/jpeg',position:{left:x,top:y,width:w,height:h},fit,alt:path.basename(file)});}

{
const s=p.slides.add();s.background.fill=ink;
await image(s,'spity/public/images/brand/escalade-falaise-coucher-soleil.jpeg',790,0,490,720,'cover');
text(s,'SPITY',64,96,660,90,74,true,'#FFFFFF');text(s,'Coordonner et piloter\nun projet logiciel',64,244,690,150,46,true,'#FFFFFF');text(s,'Dorian Joly\nRNCP39583 · Bloc 3',64,506,620,90,28,false,'#DAE5DE');
const notes='Durée : 30 secondes. Présenter le sujet et annoncer le fil conducteur : organiser une sortie avec un partenaire et un club. La présentation combine le logiciel et ses traces réelles avec un cas pédagogique de pilotage explicitement fictif. Ne pas présenter les rôles fictifs comme des collègues réels. Source : référentiel Bloc 3 p. 11-14. Visuel : fichier de marque existant du dépôt Spity, utilisé comme illustration et non comme photo de l’équipe.';
s.speakerNotes.textFrame.setText(notes);plan.push({number:1,title:'Spity - Coordonner et piloter',minutes:0.5,nature:'Introduction',notes});
}
let s=slide('Un parcours pour préparer une sortie',1.5,'Produit réel et cas pédagogique',
'Durée : 1 min 30. Expliquer les deux utilisateurs, grimpeur et club. Le grimpeur recherche un partenaire et un événement ; le club gère sa sortie et ses participants. Les critères sont le matching, la traçabilité de la demande, la capacité et les droits du club. Distinguer la partie observée, la partie historique et la simulation. Les comptes de démonstration ne sont pas des personnes interrogées. Sources : dossier §1-2 ; cahier de recettes Bloc 2 ; vérification courante.');
lines(s,[['Grimpeur','Trouver un partenaire compatible et rejoindre une sortie.'],['Club','Organiser l’événement et suivre les participants autorisés.'],['Critères de succès','Parcours utilisable, capacité respectée et résultat vérifiable.']]);
s=slide('Kanban et des jalons de validation',1.5,'C.3.1 · Simulation pédagogique',
'Durée : 1 min 30. Le choix Kanban est proposé pour un petit effectif et un flux variable. Deux tâches de réalisation simultanées au maximum rendent les blocages visibles. La définition de terminé inclut les critères, la revue et la recette. Expliquer pourquoi ne pas affirmer avoir pratiqué Scrum si cela n’est pas documenté. Linear sert au backlog, Git aux changements et le classeur au pilotage chiffré. Source : dossier §3 et A01.');
table(s,[['État','Condition de passage'],['À faire','Besoin et critères compréhensibles'],['En cours','Responsable et capacité disponibles'],['À vérifier','Réalisation prête pour la recette'],['Terminé','Critères vérifiés et réserve traitée']],[300,852],178,375);text(s,'Limite proposée : deux tâches de réalisation simultanées',72,583,1110,55,26,true,green);
s=slide('Un planning de quinze jours ouvrés',1.5,'C.3.1 · Simulation pédagogique',
'Durée : 1 min 30. Présenter les jours relatifs J1 à J15 sans leur attribuer des dates historiques. Distinguer phases d’étude, mesure, conception, réalisation et restitution. La recette commence sur les fonctions prêtes et se clôt après les événements et les corrections. Les fins initiales et revues sont conservées dans le classeur. Le chemin vers la démonstration passe par la validation à J14. Source : A01 et donnees/pilotage.json.');
table(s,[['Jalon','Résultat attendu','Validation'],['J3','Périmètre et critères','Client fictif'],['J8','Parcours partenaire','CP + QA'],['J10','Écarts et arbitrage','CP + client'],['J14','Recette et corrections','CP + QA'],['J15','Démonstration et réserves','Client fictif']],[180,640,332],178,432);
s=slide('Des responsabilités explicites',1,'C.3.1 · Simulation pédagogique',
'Durée : 1 minute. Présenter CP, DEV et QA comme des rôles du scénario. Un seul A par activité. Le client décide du périmètre ; le chef de projet organise ; DEV réalise ; QA contrôle. Les disponibilités sont des hypothèses sur le lot, pas des temps historiques. Les ressources comprennent la machine, Node, MariaDB, Git, le backlog et les supports partagés. L’organisation prévoit des supports accessibles et des aménagements convenus avec les personnes. Source : A02.');
table(s,[['Rôle','Responsabilité','Capacité du lot'],['Chef de projet','Planifier, arbitrer, présenter','30 h'],['Développeur fictif','Réaliser et corriger','72 h'],['Testeur UX fictif','Recetter et restituer','30 h'],['Client fictif','Valider périmètre et résultats','3 points']],[350,510,292],180,380);
s=slide('À J10, la prévision atteint 117 heures',2,'C3.2.1 · Simulation pédagogique',
'Durée : 2 minutes. Expliquer chaque indicateur avec son dénominateur : cinq tâches terminées sur dix, avec des tailles différentes. Les 77 heures consommées ne sont pas un taux d’achèvement. Le reste à faire de 40 heures donne une prévision de 117 heures pour 112 prévues. Le budget économique passe de 4 270 à 4 465 euros, soit +195 euros et +4,6 %. La réserve de 427 euros donne un plafond de 4 697 euros et une marge de 232 euros. Modifier une entrée du classeur pendant les questions pour montrer le recalcul. Sources : A03, classeur, données du cas.');
table(s,[['Indicateur','Référence','Prévision à J10'],['Charge','112 h','117 h'],['Budget hors réserve','4 270 €','4 465 €'],['Marge sous le plafond','427 € de réserve','232 € disponibles'],['Tâches terminées','10 tâches','5 terminées']],[480,310,362],180,385);
s=slide('Surveiller la charge et les risques',2,'C3.2.1 · Simulation pédagogique',
'Durée : 2 minutes. La charge par rôle vaut CP 29/30 h, DEV 64/72 h et QA 24/30 h. La capacité totale ne peut pas être déplacée sans vérifier les compétences. CP est proche de sa limite et doit préserver son temps d’arbitrage. Les risques prioritaires portent sur l’environnement de démonstration, la surcharge et les demandes nouvelles. Donner un déclencheur et une action, pas seulement une couleur. Une revue quotidienne traite les blocages ; deux revues hebdomadaires examinent coûts et capacité. Source : A03 et A05.');
table(s,[['Rôle','Prévision / capacité','Point de vigilance'],['CP','29 / 30 h','1 h de marge seulement'],['DEV','64 / 72 h','Pas de nouveau lot sans arbitrage'],['QA','24 / 30 h','Conserver les contrôles critiques']],[190,330,632],180,300);text(s,'Risques suivis : environnement, charge, périmètre, capacité et dépôt',72,542,1090,80,26,true,green);
s=slide('Arbitrage réel : tester le standalone',2,'C3.2.2 · Git observé et analyse rétrospective',
'Durée : 2 minutes. Le commit 689e59d du 20 juillet remplace la recette CI en développement par le serveur standalone du build. Le dossier historique rapporte l’échec d’un run pendant les compilations à froid, puis la réussite après consolidation. La comparaison des trois options est rétrospective : elle n’est pas présentée comme un compte rendu contemporain. La décision visible dans Git est le standalone. Le résultat recherché est la fidélité à l’artefact de livraison. Source : git show 689e59d ; cahier de recettes Bloc 2, consolidation standalone.');
table(s,[['Option','Effet attendu','Limite'],['Ajouter des retries','Absorber certains délais','Peut masquer la cause'],['Préchauffer le dev','Réduire les compilations','Dépend des routes'],['Tester le standalone','Aligner recette et livraison','Build préalable']],[320,435,397],182,340);text(s,'Décision visible dans le commit 689e59d du 20 juillet 2026',72,572,1100,65,27,true,green);
s=slide('Arbitrage de périmètre à J10',1,'C3.2.2 · Simulation pédagogique',
'Durée : 1 minute. Une demande supplémentaire fictive vaut 12 h DEV et 4 h QA, soit 540 euros. Elle porte le coût à 5 005 euros et la charge DEV à 76 heures pour 72 disponibles. Le scénario retient le report, avec maintien des critères de recette et décision du client fictif dans CR02. Les contributions aux topos évoquées sont un lot pédagogique ; ne pas les présenter comme une photographie de l’état actuel du code. Source : A04 et CR02.');
table(s,[['Choix','Coût final du cas','Conséquence'],['Ajouter la demande','5 005 €','308 € au-dessus du plafond'],['Réduire la recette','Qualité non démontrée','Critères engagés fragilisés'],['Reporter la demande','4 465 €','232 € de marge préservée']],[330,300,522],182,350);
s=slide('Adapter le management à la situation',2,'C3.3.1 · Simulation pédagogique',
'Durée : 2 minutes. Expliquer une posture avec des actes : écouter les contraintes, comparer les options, décider et suivre. Participatif pour estimer, persuasif pour argumenter le report, directif sur une règle critique, délégatif avec un résultat et un contrôle clairs. Ne pas confondre délégation et absence de suivi. Le management est un exercice fictif, et les collaborateurs réels restent à préciser par le candidat. Source : A05.');
lines(s,[['Participatif','Estimer et répartir les tâches avec les rôles concernés.'],['Persuasif et directif','Expliquer les arbitrages ; maintenir les critères critiques.'],['Délégatif','Confier un résultat, une autonomie et un point de contrôle.']]);
s=slide('Une décision comprise et retrouvable',2,'C3.3.1 · Simulation pédagogique',
'Durée : 2 minutes. Décrire le désaccord DEV/QA à J10 : une nouvelle fonction face au besoin de stabiliser la recette. Demander faits, impacts et aide nécessaire. La réunion est courte, les options sont préparées et le client décide du périmètre. La synthèse écrite garantit la traçabilité. Donner les adaptations possibles sans inventer un handicap réel : sous-titrage, support structuré, temps supplémentaire, travail asynchrone. Dans un contexte international, indiquer les fuseaux et vérifier la compréhension par reformulation. Source : A05.');
lines(s,[['Un désaccord traité par les faits','Besoins, capacité et critères avant la décision.'],['Une trace commune','Tâche, choix, responsable et échéance dans le compte rendu.'],['Des modalités accessibles','Supports structurés, sous-titrage, reformulation et asynchrone.']]);
s=slide('Former sur les écarts utiles au projet',3,'C3.3.2 · Simulation pédagogique',
'Durée : 3 minutes. Présenter l’échelle 0 à 3 et préciser qu’il ne s’agit pas d’une notation réelle de collaborateurs. La cible est l’autonomie sur un cas courant. CP pratique la lecture des écarts, DEV la concurrence, QA les tests navigateur et le clavier. Les six heures sont intégrées dans T03, T06 et T07, sans double comptage. La réussite est vérifiée par une exécution autonome. Si l’écart persiste, prévoir accompagnement ou besoin de renfort formulé aux RH, avec compétence, mission, durée et budget. Aucun recrutement ni achat de formation n’a été effectué. Source : A06.');
table(s,[['Rôle','Écart du cas','Action et preuve'],['CP','Pilotage : 1 → 2','1 h ; expliquer le recalcul'],['DEV','Concurrence : 1 → 2','2 h ; dernière place protégée'],['QA','Recette et clavier : 1 → 2','3 h ; scénario autonome']],[180,420,552],182,330);text(s,'6 h intégrées aux tâches · 60 € de ressources complémentaires fictives',72,550,1100,80,26,true,green);
s=slide('Le client valide des critères explicites',3,'C3.4.1 · Comptes rendus simulés',
'Durée : 3 minutes. Présenter CR01, CR02 et CR03. Ils sont explicitement fictifs et non envoyés à une personne réelle. Un compte rendu comprend avancement, écarts, décision, responsable, échéance et prochain point. Les critères relient besoin et logiciel. Les indicateurs proposés sont critères acceptés, parcours sans aide, utilité sur cinq et blocages. Une absence de répondants reste non mesurée. Décrire comment recueillir une confirmation réelle sans prétendre qu’elle existe. Sources : A07 ; référentiel p. 13-14.');
table(s,[['Point','Décision du scénario'],['J3 - Cadrage','Périmètre et critères de recette'],['J10 - Écarts','Report de la demande supplémentaire'],['J15 - Démonstration','Acceptation du périmètre avec réserves']],[410,742],180,290);text(s,'Satisfaction réelle : non mesurée\nMéthode prête : critères acceptés, autonomie, utilité et blocages',72,515,1100,110,27,true,green);
s=slide('Démonstration : préparer une sortie',6,'C3.4.2 · Application locale vérifiée',
'Durée : 6 minutes, démonstration incluse. Basculer vers le navigateur local sur 127.0.0.1:3313, avec une session grimpeur et une session club distinctes. 45 s : profil ; 75 s : matching et demande ; 75 s : événement et inscription ; 90 s : club et participants ; 45 s : capacité et clavier ; 30 s : critères et réserves. Les comptes sont des données de démonstration. En cas d’incident, annoncer le critère non revalidé et utiliser les captures datées en annexe, sans les faire passer pour une démonstration en direct. Source : A08 et preuves/verification.json.');
table(s,[['Parcours','Ce que le client vérifie'],['Profil et matching','Compatibilité du partenaire et état de la demande'],['Événement et inscription','Informations, place disponible et confirmation'],['Vue club','Participants visibles et commandes autorisées'],['Validation','Critères couverts et réserves explicites']],[430,722],180,365);
s=slide('Des décisions reliées à leurs preuves',1,'Bilan · 30 minutes de présentation au total',
'Durée : 1 minute. Rappeler que les preuves techniques sont vérifiables et datées, et que les parties de management, de budget et de comptes rendus sont un cas pédagogique fictif. Les sept compétences sont reliées aux annexes. Mentionner les limites utiles : aucune mesure réelle de satisfaction, identité de l’équipe et consignes du campus à confirmer. Ouvrir l’échange en proposant de revenir sur un arbitrage, une hypothèse du classeur ou un critère de démonstration. Source : matrice de preuves et checklist de remise.');
lines(s,[['Produit et vérifications','389 tests unitaires, 72 suites et six scénarios navigateur réussis.'],['Pilotage du cas','Planning, coûts, risques, management et validation structurés.'],['Limites explicites','Équipe réelle, retours client et consignes du campus à préciser.']]);

s=slide('Annexe : parcours partenaire',0,'Capture locale du 14 septembre 2026',
'Annexe à afficher uniquement si utile pendant les questions ou en secours. Capture de l’application locale avec données de démonstration. Source : preuves/captures/manifest.json.');
await image(s,'docs/rncp/bloc-03/preuves/captures/matching-2026-09-14.png',112,156,1056,495);
s=slide('Annexe : gestion des événements',0,'Capture locale du 14 septembre 2026',
'Annexe de secours. La capture montre le rôle club dans la base dédiée. Elle ne remplace pas une validation réelle par un client. Source : preuves/captures/manifest.json.');
await image(s,'docs/rncp/bloc-03/preuves/captures/evenements-2026-09-14.png',112,156,1056,495);
s=slide('Annexe : retrouver une preuve',0,'Correspondance avec les sept compétences',
'Annexe documentaire. Le dossier PDF contient les huit annexes et la matrice. Le classeur conserve les entrées et les formules. Les résultats courants sont dans verification.json. Sources officielles : référentiel p. 11-14, modalités p. 6/8/11, grille BC03 page unique. Le règlement spécial n’est pas fourni.');
table(s,[['Compétences','Pièces de référence'],['C.3.1 et C3.2.1','A01 à A03 ; classeur de pilotage'],['C3.2.2','A04 ; commit 689e59d'],['C3.3.1 et C3.3.2','A05 et A06'],['C3.4.1 et C3.4.2','A07, A08 et vérifications']],[480,672],182,365);

if(plan.reduce((a,b)=>a+b.minutes,0)!==30)throw new Error('Durée de présentation incorrecte');
await fs.writeFile(path.join(root,'docs/rncp/bloc-03/donnees/support-oral.json'),JSON.stringify(plan,null,2)+'\n');
const candidate=path.join(tmp,'soutenance-candidate.pptx');await(await PresentationFile.exportPptx(p)).save(candidate);
const finalPath=path.join(root,'output/presentations/soutenance-bloc-03-spity.pptx');await fs.mkdir(path.dirname(finalPath),{recursive:true});
await finalizePresentation({workspaceDir:root,candidatePath:candidate,finalPath,pythonExecutable:runtimePython,integrityValidatorPath:path.join(skill,'container_tools/inspect_presentation_package_integrity.py'),layoutValidatorPath:path.join(skill,'container_tools/inspect_presentation_layout_geometry.py'),layoutArgs:['--expected-slide-size-emu','12192000,6858000','--validate-bullet-geometry','--validate-heading-fit',...tableOwners.flatMap(n=>['--require-native-table-slide',String(n)])],requiredNativeTableOwnerSlides:tableOwners,fontPolicy:{basis:'design',families:[font]},verifyArtifactToolImport:true,receiptPath:path.join(tmp,'deck-validation.json')});
const checked=await PresentationFile.importPptx(await FileBlob.load(finalPath));
for(let i=0;i<checked.slides.items.length;i++){const b=await checked.export({slide:checked.slides.items[i],format:'png',scale:1});await fs.writeFile(path.join(tmp,`slide-${String(i+1).padStart(2,'0')}.png`),new Uint8Array(await b.arrayBuffer()));}
console.log(JSON.stringify({file:finalPath,slides:plan.length,minutes:30}));
