"""Apply the explicit fictional accessibility case to the 30-minute narrative."""
import json
from pathlib import Path

def align(slides):
    case=json.loads((Path(__file__).resolve().parents[2]/'docs/rncp/bloc-03/donnees/inclusion.json').read_text(encoding='utf-8'))
    assert case['name']=='Camille' and case['fictional']
    by_number={s['number']:s for s in slides}
    def update(n,**fields): by_number[n].update(fields)
    update(6,title='Les missions et les aménagements',script="""Le scénario distingue un chef de projet, un développeur et une testeuse QA nommée Camille. Camille est un personnage fictif malentendant. Je lui confie la préparation des critères et la recette, selon ses compétences. Ce sont les tâches T02 et T07. Sa capacité reste de trente heures pour vingt-quatre heures prévues à terminaison.

L'aménagement porte sur les échanges : consignes écrites, réunions sous-titrées et décisions accessibles après la réunion. Le chef de projet prépare ces modalités avec elle. Une heure de préparation est incluse dans les tâches de pilotage existantes. La matrice RACI conserve une autorité de décision par activité. Camille reste responsable de la recette et le client de l'acceptation du périmètre.""",nature='C.3.1, équipe et situation fictives',source='A02 ; donnees/inclusion.json. Camille est un personnage fictif. C.3.1 : référentiel RNCP39583, p. 11-12. Capacités et charges du cas conservées.',action='Présenter les trois rôles et identifier les missions T02/T07 de Camille. Distinguer sa capacité de sa charge prévue.',transition="Je vérifie ensuite les écarts de charge avant d'engager le reste du lot.")
    update(14,title='Camille, QA malentendante',nature='C3.3.1, cas pédagogique fictif',layout='table',content={'rows':[['Situation','Aménagement retenu'],*case['adaptations']],'widths':[270,882]},script="""Je rends la prise en compte du handicap concrète avec Camille, testeuse QA malentendante dans notre équipe fictive. Le besoin retenu dans ce scénario est d'accéder aux informations orales et de pouvoir participer aux décisions. Je définis les modalités avec elle, sans déduire ses compétences techniques de sa situation.

Pour les réunions, les sous-titres sont testés avant le point et une seule personne parle à la fois. L'ordre du jour est disponible à l'avance. Pour les décisions, le compte rendu indique l'action, son responsable et son échéance. Pour la formation, les consignes sont écrites et la démonstration est sous-titrée.

Je prévois un contrôle à chaque étape. À J3, Camille doit pouvoir accéder au support et reformuler une consigne. À J10, elle doit retrouver la décision et son échéance dans la synthèse. À J14, elle doit réaliser un cas sans aide. Ce sont des critères du scénario, sans résultat réel annoncé. Si les sous-titres sont insuffisants, je reprends par écrit et j'ajuste les modalités avec elle. Le fonctionnement asynchrone aide aussi les personnes absentes ou dans un autre fuseau.""",source='A02, A05, A06 et donnees/inclusion.json. Cas fictif autorisé par le référentiel p. 11 ; critères C3.3.1 p. 12 et C3.3.2 p. 13. La note d’audit du 15 septembre distingue obligation de prise en compte et composition de l’équipe.',action='Lire chaque situation et son aménagement. Terminer par les critères de vérification, sans annoncer un résultat réel.',transition="La formation doit elle aussi être accessible et conduire à un résultat observable.")
    update(16,title='Une formation accessible à Camille',script="""Le plan de formation comporte six heures : une heure pour le chef de projet, deux pour le développeur et trois pour Camille, notre testeuse QA fictive. Ces temps sont déjà compris dans les tâches du lot. Le budget de soixante euros correspond à des ressources complémentaires hypothétiques, sans achat déclaré.

Les trois heures de Camille se répartissent entre deux heures de recette navigateur et une heure de parcours clavier. Elle reçoit les consignes écrites avant l'atelier. La démonstration est sous-titrée et les échanges restent disponibles par écrit. Elle réalise ensuite le même exercice technique que celui prévu pour le rôle QA. Le besoin d'aménagement ne modifie pas le niveau de compétence attendu.

La vérification porte sur son autonomie : rejouer un cas, expliquer les préconditions, identifier le résultat et retrouver la preuve. Si une instruction reste inaccessible, nous corrigeons le support. Si une difficulté technique persiste, nous prévoyons un accompagnement et réestimons la charge. Je distingue ainsi l'accessibilité de la formation de l'acquisition de la compétence. Les résultats de cet exercice restent à constater dans le scénario.""",source='A06 ; donnees/inclusion.json. Formation QA de 3 h dans T07, déjà comprise dans les 6 h du plan. Aménagements et évaluation simulés ; aucun résultat réel attesté.',action='Montrer les 3 h QA du graphique, puis les supports adaptés et le critère de réussite autonome.',transition='Ces modalités accompagnent les jalons de suivi et de validation du client fictif.')
