"""Anchor the presentation in the dated Linear observation and detailed estimates."""
import json
from pathlib import Path

def align(slides):
    by_number={s['number']:s for s in slides}
    def update(n,**fields): by_number[n].update(fields)
    update(4,title='Le backlog Linear au 14 septembre',nature='Linear observé, 14 septembre 2026',script="""J'utilise Linear pour retrouver les sujets du projet, leurs priorités et leurs dépendances. La lecture du quatorze septembre montre vingt-cinq tickets : douze terminés, quatre à faire, un en cours, sept en backlog et un annulé. En excluant l'annulé, douze sur vingt-quatre sont terminés. Ce taux de cinquante pour cent compte des tickets de tailles différentes. Il ne signifie donc pas que la moitié du produit est livrée.

Le ticket en cours est SPI-27, l'upload sécurisé. Sa description indique que le service existe, avec des validations de persistance encore attendues avant clôture. Ce service est nécessaire à l'API de publication SPI-15 et au formulaire SPI-18. Cette dépendance explique pourquoi je traite la sécurisation du service avant d'ouvrir davantage de travaux de publication.

Dans le cas de management, je propose une limite de deux tâches de réalisation simultanées et une vérification des critères avant passage à terminé. Les vingt-quatre tickets non annulés sont affectés à Dorian dans l'outil. La répartition entre chef de projet, développeur et testeur qui suit représente une équipe fictive pour l'exercice.""",source='Lecture directe du tableau https://linear.app/spitywa/team/SPI/all et des fiches SPI-27, SPI-15, SPI-18 et SPI-6 le 14 septembre 2026. A09 et donnees/linear-2026-09-14.json. Descriptions détaillées datées du 9 septembre.',action='Lire les quatre statuts non annulés, puis expliquer la dépendance médias, API et formulaire.',transition='Je distingue ce backlog observé du lot pédagogique chiffré sur quinze jours.')
    update(7,title='Les causes des 5 heures supplémentaires',script="""Les chiffres du lot reposent maintenant sur trente activités détaillées, regroupées dans dix tâches. Chaque ligne décrit un travail identifiable, son estimation initiale, son consommé simulé à J10 et son reste à faire. Les trente estimations initiales totalisent cent douze heures. Le consommé atteint soixante-dix-sept heures et le reste à faire quarante heures. La prévision totale devient donc cent dix-sept heures.

Le graphique explique les cinq heures supplémentaires. La clarification des dépendances ajoute une heure de pilotage. Les contrôles d'accès ajoutent deux heures, la stabilisation des événements deux heures et la recette deux heures. En sens inverse, la réestimation des corrections retire deux heures. Cette économie reste une hypothèse à surveiller, elle ne justifie pas de réduire les critères de validation.

Je conserve la référence initiale et les causes d'écart pour rendre la décision traçable. Les heures sont des données du scénario, pas des temps saisis dans Linear. Les soixante-dix-sept heures consommées ne donnent pas non plus un pourcentage de fonctionnalités terminées. Pour décider, je rapproche ce consommé des livrables vérifiés et des contrôles encore nécessaires.""",source='A09, section 4 et 5 ; donnees/pilotage.json, 30 estimateDetails ; classeur Estimations et Planning. Simulation pédagogique, sans relevés horaires réels.',action='Lire chaque cause de variation puis montrer le total net de cinq heures.',transition='Ces heures ont un effet différent sur le budget selon le rôle concerné.')
    by_number[12]['source']+=' Linear SPI-22 est observé en Backlog au 14 septembre. Le chiffrage additionnel 12 h DEV et 4 h QA est une hypothèse du lot, pas une estimation extraite de ce ticket.'
    by_number[12]['action']='Montrer le rattachement de la demande au contexte SPI-22, puis comparer les coûts et la capacité DEV.'
    update(24,title='La sensibilité du budget et de la capacité',nature='Annexe, scénarios pédagogiques',content={'rows':[['Hypothèse','Prévision','Marge','Capacité'],['J10','4 465 €','232 €','Respectée'],['QA +6 h','4 645 €','52 €','Respectée'],['DEV +8 h','4 745 €','−48 €','Respectée'],['CP +2 h','4 555 €','142 €','CP : 31 / 30 h'],['Topos +16 h','5 005 €','−308 €','DEV : 76 / 72 h']],'widths':[310,240,225,377]},script="""Chaque ligne ajoute une hypothèse isolée à la prévision J10. Six heures QA consomment cent quatre-vingts euros et laissent cinquante-deux euros de marge. Huit heures DEV dépassent le budget de quarante-huit euros, malgré une capacité encore respectée. Deux heures CP conservent cent quarante-deux euros de marge mais portent sa charge à trente et une heures pour trente heures disponibles. La demande topo dépasse les deux contraintes. Les lignes ne se cumulent pas. Les formules de la feuille Pilotage permettent de modifier les heures supplémentaires et de vérifier les effets.""",source='A09 section 6 ; classeur Pilotage, sensibilité ; donnees/pilotage.json. Taux et capacités fictifs du lot.',action='Choisir un scénario dans le tableau et expliquer séparément la contrainte budgétaire et la capacité.')
